### ISSUE TITLE
JDK 1.6 Support

### ISSUE THREAD

**Issue by anidotnet** [greenmail-mail-test/greenmail#148]
It looks like greenmail-core downloaded from maven central is not compatible with jdk6. While building my project on jdk6 who has dependency on greenmail 1.5, I am getting below error:

> java.lang.UnsupportedClassVersionError: com/icegreen/greenmail/junit/GreenMailRule : Unsupported major.minor version 51.0

Is there any reason not to support jdk6?

**Comment by marcelmay** [comment]
GreenMail 1.5+ requires JDK7. For JDK6 you could use previous version 1.4.

Have a look at the description in the [download section](http://www.icegreen.com/greenmail/#download), which describes the system requirements.

The reason is that Oracle ended its support phase for JDK 1.6 quite a while ago, even for JDK 7 - and that we wanted to use some of the JDK 7 features.
