### ISSUE TITLE
escaping of SMTP folded subject lines introduces unexpected characters

### ISSUE THREAD

**Issue by palimpsestor** [greenmail-mail-test/greenmail#149]
According to the SMTP spec, long subject lines can be "folded", introducing carriage return and linefeed characters which are escaped improperly when retrieved via IMAP.

**Comment by buildscientist** [comment]
@marcelmay I'll leave this up to you since you assigned yourself #150 but it seems like we should actually have code in SimpleMessageAttributes.java that handles a folded subject line. 

It looks like JavaMail doesn't actually handle unfolding those types of subject lines and leaves it up to the application developer to handle - that is according to the Javadocs in [MimeMessage](https://javamail.java.net/nonav/docs/api/javax/mail/internet/MimeMessage.html).

> "Received headers may have been folded. The application is responsible for folding and unfolding headers as appropriate."

We could employ a regex to filter out all \r followed by \s+ and then combine the string into a single line. I would like to continue using JavaEscape as it is memory efficient when escaping/unescaping strings. I think this is a lot better than doing this: 

`text.replace("\r", "\\\r").replace("\n", "\\\n").replace("\\", "\\\\").replace("\"", "\\\"");`

which is unnecessarily creating additional String objects.

**Comment by buildscientist** [comment]
@marcelmay Actually looks like there's a built-in Javax class [MimeUtility](http://docs.oracle.com/javaee/7/api/javax/mail/internet/MimeUtility.html) which will handle unfolding the subject for you via a call to the unfold() method. 

I think we should use this.

**Comment by marcelmay** [comment]
@buildscientist : +1 for MimeUtility, good idea.

@palimpsestor, @buildscientist  : I'll add further comments in your pull request.
