### ISSUE TITLE
Verify Greenmail using Sonar in CI build

### ISSUE THREAD

**Issue by camann9** [greenmail-mail-test/greenmail#42]
+Get rid of Sonar violations

**Comment by buildscientist** [comment]
We can use [SonarQube's Nemo](http://nemo.sonarqube.org/) instance for this. It looks like we'll need to ask for permission from the maintainers to add GreenMail to the project. 

Based on this SonarQube Google Groups [thread](https://groups.google.com/forum/#!topic/sonarqube/aljQvn4hNz0) it appears that Sonar runs are pull based only. I'll see if we can have this run per build - otherwise it's counter to CI.

**Comment by buildscientist** [comment]
GreenMail is setup on [Nemo SonarQube](http://nemo.sonarqube.org/dashboard/index?id=com.icegreen%3Agreenmail-parent)

Note the following regarding pull based Sonar builds: 

```
Nemo analysis is set up to run daily. Eventually you should be able to trigger this at will, but for now it's daily.
```

Closing.
