### ISSUE TITLE
Remove dependency to commons-lang

### ISSUE THREAD

**Issue by camann9** [greenmail-mail-test/greenmail#51]
We use only one method from it

**Comment by buildscientist** [comment]
@camann9 @marcelmay 

How do you feel about using a library like - [unbescape](http://www.unbescape.org) instead of commons-lang3? 

We'd still be pulling in a dependency - but unbescape itself doesn't have any dependencies. The alternative is I pull the Java escaping specific classes out (the project is Apache 2.0 licensed) and use them in GreenMail.

**Comment by marcelmay** [comment]
Hi,

I’d rather favour to inline the method (or impl.).
Unbescape is less known than Apache commons lang, and still is >100kb.

We escape only very few < 10 elements, right?

Cheers,
Marcel

**Comment by buildscientist** [comment]
@marcelmay 

We should be escaping pretty much anything in the IMAP envelope. I'll pull the Java escaping code in from Unbescape.

**Comment by buildscientist** [comment]
Reassigned this issue to myself as I'll be pulling in the Java escaping code from Unbescape.

**Comment by buildscientist** [comment]
@camann9 @marcelmay Please code review and approve/disapprove my PR :)
