### ISSUE TITLE
Error after Update from 1.6.14 to 2.0.0 Port is null

### ISSUE THREAD

**Issue by Carsten64** [greenmail-mail-test/greenmail#549]
Hi after i have migrated vom greenmail 1.614 to 2.0.0. my tests are failing.
I am using org.apache.commons:commons-email:1.5 for sending my E-Mails. Inside the test it cannot connect to the greenmail server becouse the port is null

```
org.apache.commons.mail.EmailException: Sending the email to the following server failed : 127.0.0.1:null
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1469) ~[commons-email-1.5.jar:1.5]
	at org.apache.commons.mail.Email.send(Email.java:1496) ~[commons-email-1.5.jar:1.5]
```

Did you have a migration guide?

**Comment by marcelmay** [comment]
Hi @Carsten64 ,

you're using a library depending on JavaMail 1.x , so you must use GreenMail 1.6.x .

See documentation on version compatibilities of [JavaMail and GreenMail](https://greenmail-mail-test.github.io/greenmail/), due to JavaMail 2.x not being backward compatible:
* GreenMail 1.6 - JavaMail 1.x
* GreenMail 2.0 - JavaMail 2.0
* GreenMail 2.1 - JavaMail 2.1

**Comment by marcelmay** [comment]
... so you should use version GreenMail 1.6.14, or switch from [commons-mail](https://search.maven.org/artifact/org.apache.commons/commons-email) to a library supporting recent JavaMail 2.x .

**Comment by marcelmay** [comment]
[GreenMail/JavaMail/JakartaMail compatibility](https://github.com/greenmail-mail-test/greenmail#version-compatibility)
