### ISSUE TITLE
Mails with multiple recipients

### ISSUE THREAD

**Issue by mpschaeuble** [greenmail-mail-test/greenmail#675]
I'm currently using Greenmail 2.0.1 in JUnit5 tests and I'm not sure whether it's a bug or this is the expected behaviour: When sending a single mail to two different recipients, e.g. using
`GreenMailUtil.sendTextEmailTest("first@a.com,second@b.com", "from@localhost", "subject", "body");`, I observe the following behaviour:

- `greenMail.getReceivedMessages()` -> returns two results
- `getReceivedMessagesForDomain("a.com")` -> returns two results
- `getReceivedMessagesForDomain("b.com")` -> returns two results

I would either expect getReceivedMessages() to return a single result (because it's one mail) or both getReceivedMessagesForDomain(...) to return a single result in this case. Is my expectation wrong? How can I verify a single mail is sent by my application under test to two different recipients?

**Comment by marcelmay** [comment]
Update: Works as it should, since getReceivedMessages always operates on the raw message underneath.

The message gets duplicated per receiving user, but it is a full copy and therefore would be always found twice (for each user). A bit confusing maybe, but the match is on the raw mesages (ignoring which user received it).

I updated getReceivedMessagesForDomain description.

If you would like to access all received messages for users of a domain, you would need to find all users for a domain, and iterate over these:
```java

final ImapHostManager imapHostManager = greenMail.getManagers().getImapHostManager();
final Stream<StoredMessage> allMessagesForDomain = greenMail.getUserManager().listUser().stream()
            .filter(u->u.getEmail().toLowerCase().endsWith("mydomain.com"))
            .flatMap(u -> imapHostManager.getInbox(u).getMessages()); // Pseudo code, needs exception handling
```

**Comment by marcelmay** [comment]
Next release 2.1.0 will better support your case : #798
