### ISSUE TITLE
Move greenmail-site to its own repo

### ISSUE THREAD

**Issue by buildscientist** [greenmail-mail-test/greenmail#97]
Per a question regarding greenmail-site in issue #94 I think it would be a good idea to put greenmail-site into it's own repo. Most contributors to GreenMail aren't going to make changes to the site. 

/cc @marcelmay @waelchatila @camann9

**Comment by marcelmay** [comment]
@camann9 and I discussed this a year ago, as I had the same thought. But @camann9 convinced me to keep the site with the sources, so that you can commit source changes and document updates in one step. The site is also version specific - for example it currently already contains description of features for the next release.

**Comment by buildscientist** [comment]
Makes sense - closing issue.
